### ISSUE TITLE
Functional clone of https://github.com/MaartenDesnouck/google-apps-script ?

### ISSUE THREAD

**Issue by MaartenDesnouck** [google/clasp#1]
Seems kind of silly that you guys are making a functional clone of my tool...

**Comment by grant** [comment]
Hey @MaartenDesnouck, author here. The Apps Script team has been working on launching a new [API](https://developers.google.com/apps-script/api/), rather than just the Google Drive API, which supports creating, modifying, deploying, monitoring, and executing Apps Script projects.

Your tool along with others have tremendously helped the Apps Script community. Looking at one of the Apps Script project list: [google-apps-script-awesome](https://github.com/oshliaer/google-apps-script-awesome-list#development), there are a few community-built tools for helping build Apps Script using the Google Drive API, including your tool. I think this shows the lack in support in Apps Script tooling rather than functional clones of each other.

This tool was inspired by `git`, `yarn`, `heroku`, linux, and the [API REST endpoints](https://developers.google.com/apps-script/api/reference/rest/v1/projects), I don't think it's fair to say its a clone of anybody's tool. The project is purposely open sourced and quite lightweight (1 file).

That said, it would be _awesome_ if you'd like to contribute to this tool. You can also take any part of the code for your own use. There are still a ton of ideas of how we can make a greater developer experience using Apps Script.
