### ISSUE TITLE
Add shell functionality (`clasp run`)

### ISSUE THREAD

**Issue by rielzzapps** [google/clasp#11]
Since clasp is running authorised, it would be nice if it could leverage the execution api to add a shell functionality. 

Looking at firebase's Cloudfunctions where the shell is a powerfull tool.

**Comment by grant** [comment]
Yup. This is definitely a wish I have! Something like:

`clasp run sendEmail`

**Comment by rielzzapps** [comment]
If I find some time, I would like to get my hands dirty and do some POC and maybe it sticks ;)
Then the first question would be, would it be better to do a separate auth (because more scopes) for this?

**Comment by grant** [comment]
I haven't played around much with the execution part of the API, but this would be my general plan. LMK if you need help with the POC.

# V1
Execute functions that don't require credentials.

```js
function getPi() {
  return 3.1415;
}
```
```sh
clasp run getPi
3.1415
```

# V2
Execute functions that require Google Services (OAuth: like Gmail, Sheets...).

I think we'd have to request more specific **scopes** for `clasp` ([Current scopes](https://github.com/google/clasp/blob/master/index.js#L315)). 

Store scopes in [`appsscript.json#oauthScopes`](https://developers.google.com/apps-script/concepts/manifests).

_(TODO: Document `.clasp.json` structure)_

`clasp run sendMail`

```js
function sendMail() {
  MailApp.sendEmail("email@example.com", "Test", "hi");
}
```

# V3
Have the user re-login if they haven't auth'd the required credentials. (Requires that clasp store which credentials have been authorized per project)

Ref: https://developers.google.com/apps-script/api/reference/rest/v1/scripts/run

**Comment by rielzzapps** [comment]
Clear.

Additionally I thought of logging.
Somewhere in between the V's, a console.log statement would be nice. I am not sure if stackdriver output can be fetched in the meantime but it will lag behind. I think realtime console logging like cloudfuctions shell does is not possible with GAS.

**Comment by grant** [comment]
I think V1 is possible with [`script.run`](https://developers.google.com/apps-script/api/reference/rest/v1/scripts/run).

Logging is a fantastic idea. Let's add that as a different issue.
https://cloud.google.com/monitoring/api/v3/

**Comment by grant** [comment]
In order to run a script, you need to use your own API key with `clasp`.

## Next steps:
- Enable a user to use their own API key
- Develop clasp `run` command

**Comment by grant** [comment]
Specific next steps:

## Enable a user to use their own API key
- The first step would be to create a personal (rather than global) client ID/secret and store that in the `.clasprc.json`.
- Perhaps start the flow with: [`clasp login --own-key`](https://github.com/google/clasp/blob/master/index.ts#L443).
- This could walk you through getting a client ID/secret. Store these in [`.clasprc.json`](https://github.com/google/clasp/blob/master/index.ts#L68). This would store the credentials used for the [`oauth2Client`](https://github.com/google/clasp/blob/master/index.ts#L134-L138).

## Develop `clasp run`
- Add a new command `clasp run [method]`.
- Give an error if someone tries to use the global API client ID.
- Implement [`script.run`](https://developers.google.com/apps-script/api/reference/rest/v1/scripts/run): `clasp run printHello ["arg1", 2, {}]`
