### ISSUE TITLE
Lint Instructions

### ISSUE THREAD

**Issue by grant** [google/clasp#16]
Add instructions on how you can use 3P tools to lint Apps Script.

Try out these linters:
- https://eslint.org/docs/user-guide/command-line-interface
- https://www.npmjs.com/package/jslint
- https://www.npmjs.com/package/lint

**Comment by jondcallahan** [comment]
I am using eslint + prettier for my apps script code. It works out well, although we had to disable the "no undefined variables" rule since everything is global and managing a whitelist becomes non-trivial in large codebases.

Related: Could we add a linter to the source code in this repo? Easier to let tools handle formatting than to remember stylistic preferences when making PRs.

**Comment by grant** [comment]
@jondcallahan Feel free to add a Google style guide `.eslintrc` to this codebase. If there are some lint issues, feel free to send a PR for fixing those issues as well.

**Comment by grant** [comment]
This issue will be resolved soon with respect to linting in this repo.
We should add lint instructions with more generic Typescript + Apps Script instructions.
