### ISSUE TITLE
Error retrieving access token: Error: read ECONNRESET

### ISSUE THREAD

**Issue by OLEREO** [google/clasp#203]
## Actual Behavior
Landing page display：
> Logged in! You may close this page.

But clasp shows：
> Error retrieving access token: Error: read ECONNRESET

I use Shadowsocks VPN in China,Maybe it's related to this?

## Steps to Reproduce the Problem
  1.clasp login

## Specifications
  -  npm: '5.6.0'
  - @google/clasp@1.3.1
  - Windows 10

**Comment by grant** [comment]
I'm not sure. This error is probably because you are in China and the internet provider is blocking this API. As in, G Suite doesn't work in China.

There was a feature request to support proxies: #8

But I think you can just use a proxy with googleapis directly following these instructions:
https://www.npmjs.com/package/googleapis#using-a-proxy

I'll accept PRs for any fix you find a fix. Otherwise, I'll close this issue.
Feel free to comment here an I can reopen this issue.

**Comment by andiechu** [comment]
Did you successfully log in clasp? How did you solve it? I have the same problem and I'm also using ShadowSocks too.

**Comment by andiechu** [comment]
I've solved it. I use ShadowsocksX-NG (a SS client on Mac OSX), so the http_proxy's port is 1087 as default. So just add this env: 
`export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;`

Then run `clasp login`.

**Comment by zoudino** [comment]
Hi Andie, 

I am very new to the clasp and try to use proxy as well. However, I could not figure out the solution. When you were trying to add the env export http_proxy, were you editing on the clasp auth.ts like the following screenshot? 
![image](https://user-images.githubusercontent.com/41334363/117462614-69774c00-af81-11eb-860b-fa14df8f84d6.png)
If not, could you direct me to a right direction? Your help is very much appreciated.
