### ISSUE TITLE
.clasprc.json not found in parent directory

### ISSUE THREAD

**Issue by nirazul** [google/clasp#215]
## Expected Behavior
It would be nice if the `.clasprc.json` is also found, when it's located in a parent directory. 
Currently, it's only working in the same directory.

## Actual Behavior
I tried out the `--ownkey` parameter to log in, which was working.
As I have several projects, I then switched into a child directory. Clasp couldn't find any credentials.
I was under the impression that it doesn't matter in which directory I log in.

## Steps to Reproduce the Problem

  1. `cd` to a clasp project and then do `cd ..`
  1. `clasp login`
  1. `cd child_folder`
  1. `clasp push`

## Specifications

  - Node version: 9
  - Version: 1.3.2
  - OS: Mac

**Comment by campionfellin** [comment]
Hey @nirazul , thanks for filing this issue! We are in the process of changing the way `clasp login` works, (read https://github.com/google/clasp/issues/204 if interested). Right now when authorizing to run commands it first checks your current directory, and if `.clasprc.json` isn't there then your home directory.

The way that `clasp login` works now, is that the `--ownkey` flag saves it to your current directory, otherwise it defaults to your home directory.

The authorization check can probably be changed to check current directory and then recursively upward. @grant what do you think?

**Comment by nirazul** [comment]
@campionfellin 
Thanks for the clarification, now I'm sure that I understand how the login behaviour works currently. 

I thought about it a bit more. I think the login has ties to the document I'd like to handle with clasp. So it would make the most sense to me, when the login credentials are sorted within the `.clasp.json` file directly or at least in the same directory.
To keep this behaviour predictable, I would disallow a login or writing a `.clasprc.json` when there is no `.clasp.json` file or at least only write it globally to maintain backwards compatibility.

**Comment by grant** [comment]
Like `git` projects, we should treat local > global configs.

- `ownkey` should write a `.clasprc.json` for use in the clasp project, next to the `.clasp.json`
- All commands should look for the clasp project root (`.clasp.json`), and check for the `.clasprc.json` and use it if it exists.

It looks like the current behavior only checks the current directory for a local rc, rather than recursively checking parent directories.

Source:

`loadAPICredentials`: https://github.com/google/clasp/blob/master/src/auth.ts#L71
1. Find the project file (`.clasp.json`)
1. Check if there is a `.clasprc.json` next to the `.clasp.json` file.
1. If so, use it for the command, if not use the global.

Recursive project source (`DOTFILE.PROJECT`): https://github.com/google/clasp/blob/master/src/utils.ts#L72

I think we'll need to change `DOTFILE.RC_LOCAL` to a method, or something along those lines.
