### ISSUE TITLE
clasp push does not report Javascript lint errors

### ISSUE THREAD

**Issue by OleksandrRakovets** [google/clasp#258]
## Expected Behavior
`clasp push` of JS code with syntax error rejects to push with an error message, as it's displayed in web editor. This actually worked in v1.3.

## Actual Behavior
`push` results in `Push failed. Errors:` with no reasoning.

## Steps to Reproduce the Problem

  1. Make a syntax error in the script, e.g. put extra ; in array or object definition.
  2. `clasp push`

## Specifications

  - Node version (`node -v`): 10.6.0
  - Version (`clasp -v`): 1.4.0
  - OS (Mac/Linux/Windows): macOS 10.13.5

**Comment by campionfellin** [comment]
Hey @OleksandrRakovets thanks for the note! This was fixed in this commit: https://github.com/google/clasp/commit/272c1df69dfdddc037dba5826524327370c949fa

changing from `logError(...)` (which exits) to `console.error(...)` so it would continue and show what the errors were. This hasn't been updated on `npm` yet. @grant probably time to publish `clasp 1.4.1`?

**Comment by grant** [comment]
I've noticed this too.

Isn't 1.4.1 published?
https://www.npmjs.com/package/@google/clasp

I'll have to investigate this.

**Comment by OleksandrRakovets** [comment]
npm says it's published 2 days ago and I must have tried to update 3 days ago :)

Can confirm the correct reporting now.

Cheers for the great tool by the way! I've been waiting for it for so  many years.
