### ISSUE TITLE
Clasp tests should hit every ERROR/LOG message

### ISSUE THREAD

**Issue by campionfellin** [google/clasp#266]
To increase coverage we should try to find and hit every ERROR message:

https://github.com/google/clasp/blob/0a7ac1366acfb8db91a9600fad9cee675ecce535/src/utils.ts#L82-L114

with the tests.

Additionally, we should probably hit all the log messages as well:

https://github.com/google/clasp/blob/0a7ac1366acfb8db91a9600fad9cee675ecce535/src/utils.ts#L117-L155

**Comment by grant** [comment]
I think this issue is nice to have, but isn't necessary.

Having 100% code coverage will forever be a goal of this project. In reality, other issues are more important and this project doesn't have enough staffing (just me part time) to maintain 100% coverage. Feel free to add PRs with this issue attached though.
