### ISSUE TITLE
Command Failed: clasp push

### ISSUE THREAD

**Issue by labnol** [google/clasp#281]
The push command is failing because Clasp is unable to read the appsscript.json file in the root directory though it exists. 

The issue is specific to clasp v1.5.2 though it works with the 1.4 release. 

https://github.com/labnol/apps-script-starter/issues/2

`➜ **ls dist**
appsscript.json 
code.js         
oauth2.js

➜ **npx clasp status**
Not ignored files:
└─ dist/code.js
└─ dist/oauth2.js

Ignored files:
└─ dist/appsscript.json

➜ **npx clasp push**
Push failed. Errors:
**Project contents must include a manifest file named appsscript.**
Files to push were:
└─ dist/code.js
└─ dist/oauth2.js
`

**Comment by grant** [comment]
Thanks for the report. I'll address this issue soon.

**Comment by grant** [comment]
Hey @labnol, I spend a few minutes today trying to fix this issue.

However, I'm not sure what the problem is. This is my config:

# Files

## `.clasp.json`
```json
{
  "scriptId":"11AIejfE3_Qbmh0BO1Yb0g75c0giLjWlghFcALj9BI6OTLHI7JyDU-Pph",
  "rootDir": "dist"
}
```

## `dist/foo.js`
```js
Logger.log('hi');
```

## `dist/appsscript.json`
```json
{
  "timeZone": "America/New_York",
  "dependencies": {
  },
  "exceptionLogging": "STACKDRIVER"
}
```

# Issue

It seems like you're looking to have the `appsscript.json` file be separate from the Apps Script project (as in, outside of `dist/`). This doesn't seem like a good idea since that file is part of the source files for the Apps Script project.

For your config, can you make sure that `appsscript.json` is in your `rootDir`, or copy it there?

I don't really want to look at both your `.clasp.json` directory _and_ your `rootDir` directory to find the manifest file.

**Comment by labnol** [comment]
Hello @grant - The manifest file is in the `rootdir` itself and the clasp push command is still ignoring it for some reason.

I upgraded to Clasp 1.5.3 today and it seems to have resolved the issue. Thanks for the help.
