### ISSUE TITLE
Local .clasprc.json Support

### ISSUE THREAD

**Issue by johnnyasantoss** [google/clasp#483]
## Expected Behavior
Be able to use only local `.clasprc.json` for CI environments

## Actual Behavior
Ignores completely the local file and prefers the one on the user folder, which is not CI friendly.

## Steps to Reproduce the Problem

1. Move the file @ `~/.clasprc.json` to `./` (your project folder)
2. Try any command that needs authentication. eg. `clasp versions`, `clasp deploy`, etc...

## Specifications

- Node version (`node -v`): `v10.13.0`
- Version (`clasp -v`): `1.7.0`
- OS (Mac/Linux/Windows): probably any but now I'm using Windows 10

**Comment by johnnyasantoss** [comment]
It would be great if the one at the user folder would be something like a fallback/merge as `.gitignore` or `.npmrc` does.

**Comment by grant** [comment]
Hey @johnnyasantoss, I hear you, but I think this issue is already being tracked in other issues.

Example:
https://github.com/google/clasp/issues/225

**Comment by Luzifer** [comment]
Having the same issue local `.clasprc.json` handling is fully broken.

This is broken since introduction of the `local` parameter here:
https://github.com/google/clasp/blob/cc6673905c69f7ee364d07ab68ccecf6eae3f0f6/src/auth.ts#L189

As the `local` parameter is never set (and therefore is always `false`), the global config is always used.

This is **not** related to service account usage as described in #225 but a breakage introduced in 87a48109. @grant please re-open this and treat as a bug, not a feature-request.

**Comment by grant** [comment]
I've opened this issue asking for local credential support.

**Comment by leehen** [comment]
Still has the same issue for 2.3.0. Any work around?

**Comment by Nu11u5** [comment]
This seems to be related to #42 and should probably be merged.

There was previously a discussion about adding a `--local` parameter [here](https://github.com/google/clasp/pull/447#discussion_r240480830).

**Comment by cattermo** [comment]
I'm still running 1.7.0 due to this feature missing...

**Comment by PopGoesTheWza** [comment]
Try replacing `@google/clasp` 2.3.0 with `forked-clasp` which is more advanced: https://github.com/PopGoesTheWza/clasp/blob/forked/docs/config-files.md

```shell
npm uninstall -g @google/clasp
npm install -g forked-clasp
```

**Comment by PopGoesTheWza** [comment]
Fixed in https://github.com/google/clasp/releases/tag/v2.3.1
