### ISSUE TITLE
Document tsconfig.json support

### ISSUE THREAD

**Issue by grant** [google/clasp#561]
## Expected Behavior

clasp should document `tsconfig.json` in docs/typescript.md.

## Actual Behavior

clasp supports `tsconfig.json`, but we don't document it.

**Comment by grant** [comment]
Also check if this feature is working properly. For example, change `target: 'es6'`.

**Comment by GitTom** [comment]
Yes, that would be great.

For example, is there some way to configure TS so it doesn't show an error (ts 2584) on console/stackdriver statements?  

I believe one option is to specify lib as DOM...  
```
"compilerOptions": {
        "lib": [
            "dom"
        ]
}
```
but that seems odd because it is technically incorrect and feels like using a sledgehammer on the problem.  Maybe there is a better solution?

**Comment by takanakahiko** [comment]
@GitTom Would you please create a new Issue and present the specific situation where the error occurs?

**Comment by GitTom** [comment]
@takanakahiko Ok, created #566.
