### ISSUE TITLE
MimeType problems with TS and GAS

### ISSUE THREAD

**Issue by michaelu123** [google/clasp#818]
In GAS, code.gs, I had `...folder.getFilesByType(MimeType.PDF)`. After converting this to code.ts in VSCode, MimeType is flagged as undefined. I can write `...folder.getFilesByType(GoogleAppsScript.Base.MimeType.PDF)`. Now MimeType is defined, but the enum PDF cannot be assigned to a string (getFilesByType has signature getFilesByType(mimeType: String)).  When I write `...folder.getFilesByType(GoogleAppsScript.base.MimeType.PDF.toString())`, VSCcode has no problems. After clasp push, in code.gs, I see   `...folder.getFilesByType(GoogleAppsScript.Base.MimeType.PDF.toString())`, and the script fails with `ReferenceError: GoogleAppsScript is not defined`.
What is the correct way to code this? Btw, in node_modules/@types/google-apps-script/google-apps-script.base.d.ts, I find the lines 
```
// conflicts with MimeType in lib.d.ts
// declare var MimeType: GoogleAppsScript.Base.MimeType;
```
I work around this by calling ...getFilesByType('application/pdf'), but I still wonder, where the problem originates.

**Comment by PopGoesTheWza** [comment]
`@types/google-apps-script` is not covered here.

But your issue is likely fixed by adding the line below in your code:

```ts
declare var MimeType: GoogleAppsScript.Base.MimeType
```

And if there is an issue with `MimeType.PDF` not being typed as `string`, I would rather try to cast it (`MimeType.PDF as unknown as string`) before going the `.toString()` hazardous path.
