### ISSUE TITLE
error "ReferenceError: xx is not defined" when extends class

### ISSUE THREAD

**Issue by peterweb2005** [google/clasp#850]
### issue reference

https://issuetracker.google.com/issues/192152736

### more description

filename: AAAA.ts
```
(any parent class)
```

filename: AAAA1.ts

```
(any extends the parent class)
```

ie:
- (child filename) AAAA1.ts > (parent filename) AAAA.ts, it works
- child filename< parent filname, it failed

**Comment by sqrrrl** [comment]
This is more of an apps script issue, and specifically the V8 runtime, than clasp. Apps Script doesn't really have modules and imports in the same way that JS/TS does. With V8, the file order matters in terms of how code is parsed, and referencing a global in one file before it's defined can cause an error. See https://developers.google.com/apps-script/guides/v8-runtime/migration

 Because order matters, clasp sorts the files by name so they're uploaded in a consistent/predictable order. You can exploit that to get the ordering correct.

The alternative approach is to use a different build pipeline. For example, write code with imports so dependencies are clearly expressed, then transpile and bundle into a single JS using rollup or something similar. Then use clasp to push the bundled code.

**Comment by ryancwalsh** [comment]
This problem is kicking my butt. If I had known ahead of time that `.gs` files don't really support TypeScript, I wouldn't have spent so many hours converting them just now.

I've unsuccessfully tried the workarounds at https://github.com/google/clasp/blob/e851215b8abe4de282c62c4d61076c85e89a56ba/docs/typescript.md#typescript-support and https://github.com/google/clasp/issues/796#issuecomment-663966924 and am not sure what else to try at this point.

If I figure something out, I'll post here.

**Comment by paesku** [comment]
I have been there too.

**Comment by sqrrrl** [comment]
I'm inclined to remove typescript support from clasp if/when there's a next major version where we can break things. It doesn't really do the things people expect and I'd rather clasp stay focused on sync/project settings and leave compilation to better suited tools.

**Comment by paesku** [comment]
@sqrrrl I can understand that and I think it's totally valid to focus on the sync part and let the users manage their transpilation/complilation with the tools of their choice. There are many ways documented how things can be done.
Having the clasp project is already a huge win! Thanks therefor.

**Comment by peterweb2005** [comment]
my workaround: parent class should have lower alphabet order, 
eg: AppService extends 1AppServiceBase
