### ISSUE TITLE
Clasp create makes .clasp.json file in $HOME directory

### ISSUE THREAD

**Issue by campionfellin** [google/clasp#92]
## Expected Behavior

Clasp create should put the .clasp.json file in the current directory.

## Actual Behavior

It makes it in ~/.clasp.json

## Steps to Reproduce the Problem

  1. `mkdir test && cd test`
  2. `clasp create helloworld`
  3. `ls -a`
  4. `cat ~/.clasp.json`

## Specifications

  - Node version (`node -v`): v8.9.4
  - Version (`npm list -g | grep clasp`): @google/clasp@1.1.5
  - OS (Mac/Linux/Windows): macOS 10.13.3 High Sierra

**Comment by diminishedprime** [comment]
Could you try running this?
```
cd /tmp
mkdir helloworld
cd helloworld
clasp create helloworld
cat .clasp.json
```
Since clasp uses `findParentDir` to find the location of the `.clasp.json` file, if you have a `.clasp.json` file in your home directory, and you are navigated somewhere under your home directory (a very likely scenario), then it will just use that one as the .clasp.json file instead of creating a new one. If you delete the `.clasp.json` file in your home directory, you'll likely fix your problem.

**Comment by grant** [comment]
Hmm. I think this is because you ran `clasp create` at some point in `~`. We use the highest level `.clasp.json` in your file tree as your clasp project (so that you can run `clasp` in any subdir, like `git`).

Remove the root `~/.clasp.json`. I think normal `clasp create` works properly.

Nested clasp projects is not really recommended right now (Ideally it'd be like nested `.git`).

**Comment by campionfellin** [comment]
Thanks for the help, this solved my problem. I'll go ahead and close this issue and let us continue in https://github.com/google/clasp/issues/97

**Comment by antony** [comment]
This still happens. In fact, `clasp login` always creates it in your homedir. There aren't any other ways that I can see.

```
ant@xeno  ~/Projects/gas-boilerplate  clasp login       
Logging in globally...
🔑 Authorize clasp by visiting this url:
https://accounts.google.com/...

Authorization successful.

Default credentials saved to: ~/.clasprc.json (/home/ant/.clasprc.json).
```

**Comment by PopGoesTheWza** [comment]
@antony even though the documentation could be better worded, `.clasprc.json` is located in the user's homedir unless one uses the `--creds` option.
<https://github.com/google/clasp#login>
